#+title: Project 1
#+author: Author

# see https://github.com/timflutre/perso/blob/master/emacs
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \textwidth 16cm
#+latex_header: \oddsidemargin 0.5cm
#+latex_header: \evensidemargin 0.5cm

* Preamble

This document was generated from a text file in the org format.
See [[http://orgmode.org/][org-mode]] in the free software [[http://www.gnu.org/software/emacs/][Emacs]].
For non-Emacs user, [[http://johnmacfarlane.net/pandoc/][pandoc]] is the solution.

Note however, that Emacs is much preferred because, contrary to it, pandoc can't execute code while processing an org file to PDF or HTML.
Moreover, Emacs and org-mode are not language-specific, e.g. not restricted to R or Python (see examples below).

Example of an equation written in [[http://www.latex-project.org/][LaTeX]] ([[https://en.wikibooks.org/wiki/LaTeX][book]]): $y_i \sim \mathcal{N}(\mu, \sigma^2)$

Example of an unordered list:
- $\mu$
- $\sigma$

Example of an ordered list:
1. $\mu$
2. $\sigma$

Example of *bold*, /italics/, _underlined_, =verbatim=, ~code~, +strike-through+.

Example of a table:
| header1 | header2 |
|---------+---------|
| a       |       1 |
| b       |       2 |

# warning, the following examples don't work with pandoc (only with Emacs):
Example of an included plot from R:
#+begin_src R :file test.pdf :results graphics :exports both
hist(rnorm(10^4), breaks="FD")
#+end_src

Example of an executed command from Python:
#+begin_src python :results output :exports both
print "%i + %i = %i" % (2, 2, 4)
#+end_src

Example of an executed command from Bash:
#+begin_src sh :results output :exports both
echo "Hello World!"
#+end_src

* Overview
This document contains the documentation for project 1.
This project is part of a presentation which teaches the fundamentals of reproducible research.

The project directory is organized as advised by Noble ([[http://dx.doi.org/10.1371/journal.pcbi.1000424][PLoS Computational Biology 2009]]):

On any Unix-like system, it is easily done with the following commands:
#+begin_src sh
touch AUTHORS COPYING README; mkdir -p doc data src bin results
#+end_src

On any Unix-like system, it can also be easily compressed and transferred:
#+begin_src sh
cd ..; tar -czvf project2.tar.gz \
--exclude=project2/data/data_extern \
--exclude="*~" --exclude=".*" project2
#+end_src

* Data
Just as an example:
#+begin_src sh
cd data/
wget ftp://ftp.ensemblgenomes.org/pub/plants/release-24/fasta/vitis_vinifera/dna/Vitis_vinifera.IGGP_12x.24.dna.genome.fa.gz
#+end_src

* Results
#+begin_src sh
cd results/
#+end_src
